<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Asynchronous JavaScript</title>
</head>

<body>
    <h1>Asynchronous JavaScript</h1>
    <script>

        ////////////////////////////////////////////////////////////
        // making AJAX calls with Fetch and Promises
        const crossUrl1 = 'https://crossorigin.me/';
        const crossUrl2 = 'https://cors-anywhere.herokuapp.com/';
        const metaweatherUrl1 = 'https://www.metaweather.com/api/location/search/?query=san';
        const metaweatherUrl2 = 'https://www.metaweather.com/api/location/2487956';
        // fetch() returns a Promise<Response> object
        // so, it completes with a Response object... actually Response is an interface
        // what is a Response interface?
        // https://developer.mozilla.org/en-US/docs/Web/API/Response
        // Response implements Body, and among the methods Body has,..
        // Body.json() : Takes a Response stream and reads it to completion.
        // It returns a promise that resolves with the result of parsing the body text as JSON.
        // fetch(crossUrl2 + metaweatherUrl1)
        // .then(result => {
        //     console.log(result);
        //     return result.json();
        // })
        // .then(json => { // result json is actually an array
        //     //console.log(JSON.stringify(json));
        //     console.log(json);
        //     console.log(JSON.stringify(json));
        // });
        function getWeather(woeid) {    // woeid : where on earth id
            const crossUrl = 'https://cors-anywhere.herokuapp.com/';
            const metaweatherUrl = 'https://www.metaweather.com/api/location/';
            fetch(crossUrl + metaweatherUrl + woeid)    // it retruns a Promise<Response>, Response is an object with header property and actual response contents
                .then(response => {
                    console.log(response);
                    return response.json();   // takes a Response stream and reads it to completion
                    // It returns a promise that resolves with the result of parsing the body text as JSON
                })
                .then(json => { // JSON object returned
                    console.log(json);
                    const today = json.consolidated_weather[0];
                    console.log(`Temperatures in ${json.title} stay between ${today.min_temp} and ${today.max_temp}`);
                })
                .catch(error => console.log(error));
        }

        //getWeather(2487956);
        //getWeather(44418324324);    // NOT FOUND (404)


        // async/await version
        async function getWeatherAW(woeid) {
            try {                
                const crossUrl = 'https://cors-anywhere.herokuapp.com/';
                const metaweatherUrl = 'https://www.metaweather.com/api/location/';
                const result = await fetch(crossUrl + metaweatherUrl + woeid);
                const json = await result.json();
                console.log(json);
                const today = json.consolidated_weather[0];
                console.log(`Temperatures in ${json.title} stay between ${today.min_temp} and ${today.max_temp}`);
                return json;
            } catch(error) {
                alert(error);
            }
        }

        let dataSanFrancisco;
        // an async function returns a Promise<return type>
        getWeatherAW(2487956).then(json => dataSanFrancisco = json).then(() => console.log(dataSanFrancisco));  // log file is fine but below...
        console.log(dataSanFrancisco);  // undefined
        //getWeatherAW(44418324324);    // NOT FOUND (404)


        // blocked by CORS policy
        // fetch('https://cors-anywhere.herokuapp.com//https://www.metaweather.com/api/location/search/?lattlong=50.068,-5.316')
        // .then(result => {
        //     console.log(result);
        //     return result.json();
        // })
        // .then(jsonString => {
        //     console.log(jsonString);
        // })
        // .catch(error => console.log(error));

        // fetch('https://cors-anywhere.herokuapp.com//https://www.metaweather.com/api/location/search/?lattlong=50.068,-5.316')
        // .then(response => {
        //     return response.json();
        // })
        // .then(myJson => {
        //     console.log(JSON.stringify(myJson));
        // });

        // fetch('https://cors-anywhere.herokuapp.com/https://himate.hyundai-ce.com/Page/Asmx/AppService.asmx?op=PG_RDMB0200_MACHINE_INFO?MACHINE_NO=HHKHW600EF0000048&USER_ID=A480851')
        // .then(response => {
        //     console.log(response);
        //     return response.json();
        // })
        // .then(jsonString => {
        //     console.log(jsonString);
        // });




        // const second = () => {
        //     setTimeout(() => {
        //         console.log('async hey there!');
        //     }, 2000);
        // }
        // const first = () => {
        //     console.log('hey there!');
        //     second();
        //     console.log('end!');
        // }
        // first();

        // callback hell -> needs promises!!
        // promise : object that keeps track about whether a certain event has happened already or not
        // and determines what happenes after the event has happened
        // implements the concept of a future value that we're expecting
        /*
        function getRecipies() {
            setTimeout(() => {  // asynchronous function ... simulates behavior of servers
                const recipeId = [345, 234, 998, 400];
                console.log(recipeId);

                setTimeout((id) => {    // another asynchronous behavior
                    const recipe = {
                        name: 'fresh tomato pasta',
                        publisher: 'Jonas'
                    };
                    console.log(`${id}: ${recipe.name}`);

                    setTimeout((publisher)=>{
                        const recipe = {
                            name: 'Italian pizza',
                            publisher: 'Jonas'
                        };
                        console.log(recipe);
                    }, 1500, recipe.publisher);

                }, 1500, recipeId[3])
            }, 1500);
        }
        getRecipies();
        */

        // the Promise object represents the eventual completion (or failure) of an
        // asynchronous operation, and its resulting value

        // new Promise(executor);
        // executor : a function that is passed with the arguments 'resolve' and 'reject'.
        // the executor function is executed immediately by the Promise implementation,
        // passing resolve and reject functions (the executor is called before the Promise
        // constructor even returns the created object).
        // the 'resolve' and 'reject' functions, when called, resolve or
        // reject the promise, respectively. the executor normally initiates some
        // asynchronous work, and then, once that completes, either calls
        // the 'resolve' function to resolve the promise or else rejects it
        // if an error occured. if an error is thrown in the executor function,
        // the promise is rejected. the return value of the executor is ignored.

        // a Promise is in one of these states:
        // 1) pending: initial state, neither fulfilled nor rejected
        // 2) fulfilled: meaning that the operation completed successfully
        // 3) rejected: meaning that the operation failed
        // a pending promise can either be fulfilled with a value, or rejected with a reason (error)
        // when either of these options happens, the associated handlers queued up by a promise's
        // 'then' method are called. (if the promise has already been fulfilled or rejected when
        // a corresponding handler is attached, the handler will be called, so there is no race condition
        // between anasynchronous operation completing and its handlers being attached)

        /*

        const getIDs = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve([345, 234, 998, 400]);
            }, 1500);
        }); // executor is called before the promise constructor even returns the created object

        const getRecipe = recID => {
            return new Promise((resolve, reject) => {
                setTimeout((id) => {
                    const recipe = {
                        title: 'fresh tomato pasta',
                        publisher: 'Jonas'
                    };
                    resolve(`${id}: ${recipe.title} by ${recipe.publisher}.`);
                }, 1500, recID);
            });
        };

        const getRelated = publisher => {
            return new Promise((resolve, reject) => {
                setTimeout((pub) => {
                    const recipe = {
                        title: 'Italian pizza',
                        publisher: 'Jonas'
                    };
                    resolve(`see also ${publisher}\'s ${recipe.title}`);
                }, 1500, publisher);
            });
        };

        ////////////////////////////////////////////////////////////
        // consuming Promises in traditional way!
        // making a promise chain

        // getIDs
        // .then(IDs => {      // .then() returns a Promise again!!
        //     console.log(IDs);
        //     return getRecipe(IDs[3]);   // executor function is executed immediately by the Promise implementation
        // })
        // .then(recipe => {
        //     console.log(recipe);
        //     return getRelated('Jonas');
        // })
        // .then(relatedString => {
        //     console.log(relatedString);
        // })
        // .catch(error => {
        //     console.log("error")
        // });
        // promise error handling can be done in 2 ways
        // 1. callbackfk in second argument to then() method
        // 2. callbackfk in catch() method ===> recommended


        ////////////////////////////////////////////////////////////
        // consuming Promises with Async/Await!!
        async function getRecipesAW(){
            const IDs = await getIDs;
            console.log(IDs);
            const recipe = await getRecipe(IDs[3]);
            console.log(recipe);
            const related = await getRelated('Jonas');
            console.log(related);

            return related; // an async function always returns a promise
                            // and by returning, the promise is settled as resolved
        }
        // not working (pending)
        // const recipe = getRecipesAW();
        // console.log(recipe);

        //
        getRecipesAW().then(result => console.log(result));
        */

    </script>
</body>

</html>